FROM amazoncorretto:19-alpine-jdk
VOLUME /tmp
ARG JAR_FILE
ARG AGENT_ARG
ENV AGENT_ENV=${AGENT_ARG}
ARG NEWSGEARS_DEVELOPMENT
ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD
ARG SPRING_DATASOURCE_SCHEMA
ARG SPRING_REDIS_HOST
ARG SPRING_REDIS_PASSWORD
ARG NEWS_API_KEY
ARG NEWS_API_DISABLED
ARG NEWS_API_DEBUG_SOURCES
COPY ${JAR_FILE} app.jar
ENV NEWSGEARS_DEVELOPMENT ${NEWSGEARS_DEVELOPMENT}
ENV SPRING_DATASOURCE_URL ${SPRING_DATASOURCE_URL}
ENV SPRING_DATASOURCE_USERNAME ${SPRING_DATASOURCE_USERNAME}
ENV SPRING_DATASOURCE_PASSWORD ${SPRING_DATASOURCE_PASSWORD}
ENV SPRING_DATASOURCE_SCHEMA ${SPRING_DATASOURCE_SCHEMA}
ENV SPRING_REDIS_HOST ${SPRING_REDIS_HOST}
ENV SPRING_REDIS_PASSWORD ${SPRING_REDIS_PASSWORD}
ENV NEWS_API_KEY ${NEWS_API_KEY}
ENV NEWS_API_DISABLED ${NEWS_API_DISABLED}
ENV NEWS_API_DEBUG_SOURCES ${NEWS_API_DEBUG_SOURCES}
ENTRYPOINT java ${AGENT_ENV} -Djava.security.egd=file:/dev/./urandom -jar /app.jar
